HizmetPortal/Controllers/AdminDuyurularController.cs
using BusinessLayer_HizmetPortal.Concrate;
using BusinessLayer_HizmetPortal.ValidationRules;
using DataAcessLayer_HizmetPortal.Concrate;
using DataAcessLayer_HizmetPortal.EntityFramework;
using EntityLayer_HizmetPortal.Concrate;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HizmetPortal.Controllers
{
    public class AdminDuyurularController : Controller
    {
        // GET: AdminDuyurular
        DuyurularManager dm = new DuyurularManager(new EfDuyurularDal());
        Context context = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var duyurulars = dm.Getlist();
            return View(duyurulars);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Duyurular duyurular)
        {
            DuyurularValidator duyurularValidator = new DuyurularValidator();
            ValidationResult results = duyurularValidator.Validate(duyurular);

            if (results.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);
                    string yol = "~/Image/" + dosyaAdi + uzanti;
                    Request.Files[0].SaveAs(Server.MapPath(yol));
                    duyurular.DuyurularImage = "/Image/" + dosyaAdi + uzanti;
                }
                dm.DuyurularAdd(duyurular);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var failure in results.Errors)
                {
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(duyurular);
            }         
            
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            var duyurularvalue = dm.GetBuyID(id);
            return View(duyurularvalue);
        }

        [HttpPost]
        public ActionResult Edit(Duyurular duyurular)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + dosyaAdi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                duyurular.DuyurularImage = "/Image/" + dosyaAdi + uzanti;
            }
            dm.EditDuyurular(duyurular);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var hizmetlervalues = dm.GetBuyID(id);
            dm.DeleteDuyurular(hizmetlervalues);
            return RedirectToAction("Index");
        }
        public ActionResult ToggleStatus(int id)
        {
            dm.DuyurularToggleStatus(id);
            return RedirectToAction("Index");
        }
    }
}

HizmetPortal/Views/AdminDuyurular/Create.cshtml
@model EntityLayer_HizmetPortal.Concrate.Duyurular
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Yeni Duyuru Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("Create", "AdminDuyurular", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.Label("Duyuru Image")
        <input type="file" name="DuyurularImage" />
        <button type="submit" class="btn btn-primary">Ekle</button>
    </div>
}

HizmetPortal/Views/AdminDuyurular/Edit.cshtml
@model EntityLayer_HizmetPortal.Concrate.Duyurular
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Duyurlar Güncelleme Sayfası</h1>
<br />
@using (Html.BeginForm("Edit", "AdminDuyurular", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.Label("Duyuru Id")
        @Html.TextBoxFor(x => x.DuyurularId, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Duyuru Image")
        <input type="file" name="DuyurularImage" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Güncelle</button>
}

HizmetPortal/Views/AdminDuyurular/Index.cshtml
@using EntityLayer_HizmetPortal.Concrate
@model List<Duyurular>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div style="overflow-x:auto;">
    <table class="table table-bordered">
        <tr>
            <th>DuyurularId</th>
            <th>DuyurularImage</th>
            <th>DuyurlarStatus</th>
            <th>DuyurularStatusButton</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DuyurularId</td>
                <td>@item.DuyurularImage</td>
                <td>@item.DuyurularStatus</td>
                <td>
                    @if (item.DuyurularStatus)
                    {
                        <a href="/AdminDuyurular/ToggleStatus/@item.DuyurularId" class="btn btn-danger">
                            Devre Dışı
                        </a>
                    }
                    else
                    {
                        <a href="/AdminDuyurular/ToggleStatus/@item.DuyurularId" class="btn btn-success">
                            Aktif Et
                        </a>
                    }
                </td>
                <td><a href="/AdminDuyurular/Edit/@item.DuyurularId" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/AdminDuyurular/Delete/@item.DuyurularId" class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </table>
</div>
<br />
<a href="/AdminDuyurular/Create" class="btn btn-info">Yeni Duyuru</a>