HizmetPortal/Controllers/AdminProjectController.cs
using BusinessLayer_HizmetPortal.Concrate;
using BusinessLayer_HizmetPortal.ValidationRules;
using DataAcessLayer_HizmetPortal.Concrate;
using DataAcessLayer_HizmetPortal.EntityFramework;
using EntityLayer_HizmetPortal.Concrate;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HizmetPortal.Controllers
{
    public class AdminProjectController : Controller
    {
        ProjectManager pm = new ProjectManager(new EfProjectDal());
        StageManager sm = new StageManager(new EfStageDal());
        Context context = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var projects = pm.ProjectGetAll();
            return View(projects);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Stages = sm.StageGetAll();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Project project)
        {
            ProjectValidator projectValidator = new ProjectValidator();
            ValidationResult results = projectValidator.Validate(project);

            if (results.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);
                    string yol = "~/Image/" + dosyaAdi + uzanti;
                    Request.Files[0].SaveAs(Server.MapPath(yol));
                    project.ProjectImage = "/Image/" + dosyaAdi + uzanti;
                }


                pm.ProjectAdd(project);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var failure in results.Errors)
                {
                    ModelState.AddModelError(failure.PropertyName, failure.ErrorMessage);
                }
                return View(project);
            }         
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var projectvalue = pm.ProjectGetById(id);
            ViewBag.Stages = sm.StageGetAll(); // Bu satır eksik.
            return View(projectvalue);
        }

        [HttpPost]
        public ActionResult Edit(Project project)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + dosyaAdi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                project.ProjectImage = "/Image/" + dosyaAdi + uzanti;
            }
            pm.ProjectUpdate(project);
            return RedirectToAction("Index");
        }

        public ActionResult ToggleStatus(int id)
        {
            pm.ProjectToggleStatus(id);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var projectvalue = pm.ProjectGetById(id);
            pm.ProjectDelete(projectvalue);
            return RedirectToAction("Index");
        }
    }
}

HizmetPortal/Views/AdminProject/Create.cshtml
@model EntityLayer_HizmetPortal.Concrate.Project

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Yeni Proje Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("Create", "AdminProject", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group"> 
        @Html.Label("Proje Başlığı")
        @Html.TextBoxFor(x => x.ProjectTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProjectTitle)
        <br />
        @Html.Label("Proje Açıklaması")
        @Html.TextAreaFor(x => x.ProjectDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ProjectDescription)
        <br />
        @Html.Label("Proje Görseli")
        <input type="file" name="ProjectImage" />
        <br />
        @Html.Label("Aşama Seçiniz")
        <select class="form-control" name="StageId">
            @foreach (var stage in ViewBag.Stages)
            {
                <option value="@stage.StageId">@stage.StageName</option>
            }
        </select>
        @Html.ValidationMessageFor(x => x.StageId)
        <br />
        <button type="submit" class="btn btn-primary">Ekle</button>
    </div>
}

HizmetPortal/Views/AdminProject/Edit.cshtml
@model EntityLayer_HizmetPortal.Concrate.Project

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Proje Güncelleme Sayfası</h1>
<br />
@using (Html.BeginForm("Edit", "AdminProject", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.Label("Project Id")
        @Html.TextBoxFor(x => x.ProjectId, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Project Title")
        @Html.TextBoxFor(x => x.ProjectTitle, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Project Description")
        @Html.TextAreaFor(x => x.ProjectDescription, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Project Image")
        <input type="file" name="ProjectImage" class="form-control" />
    </div>
    @Html.Label("Aşama seçiniz")
    <select class="form-control" name="StageId">
        @foreach (var stage in ViewBag.Stages)
        {
            <option value="@stage.StageId">@stage.StageName</option>
        }
    </select>
    <button type="submit" class="btn btn-success">Güncelle</button>
}

HizmetPortal/Views/AdminProject/Index.cshtml
@using EntityLayer_HizmetPortal.Concrate
@model List<Project>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div style="overflow-x:auto;">
    <!-- Bu satır tabloyu sarmalayan div'in başlangıcı -->
    <table class="table table-bordered">
        <tr>
            <th>ProjectId</th>
            <th>ProjectTitle</th>
            <th>ProjectDescription</th>
            <th>ProjectImage</th>
            <th>StageId</th>
            <th>ProjectStatus</th>
            <th>ProjectStatusButton</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ProjectId</td>
                <td>
                    @(item.ProjectTitle != null ? (item.ProjectTitle.Length > 10 ? item.ProjectTitle.Substring(0, 10) + "..." : item.ProjectTitle) : "Bilgi yok")
                </td>
                <td>
                    @(item.ProjectDescription != null ? (item.ProjectDescription.Length > 20 ? item.ProjectDescription.Substring(0, 20) + "..." : item.ProjectDescription) : "Bilgi yok")
                </td>
                <td>@item.ProjectImage</td>
                <td>@item.StageId</td>
                <td>@item.ProjectStatus</td>
                <td>
                    @if (item.ProjectStatus)
                    {
                        <a href="/AdminProject/ToggleStatus/@item.ProjectId" class="btn btn-danger">
                            Devre Dışı
                        </a>
                    }
                    else
                    {
                        <a href="/AdminProject/ToggleStatus/@item.ProjectId" class="btn btn-success">
                            Aktif Et
                        </a>
                    }
                </td>
                <td><a href="/AdminProject/Edit/@item.ProjectId" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/AdminProject/Delete/@item.ProjectId" class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </table>
</div> <!-- Bu satır tabloyu sarmalayan div'in sonu -->
<br />
<a href="/AdminProject/Create" class="btn btn-info">Yeni Proje</a>