HizmetPortal/Controllers/AdminHizmetlerController.cs
using BusinessLayer_HizmetPortal.Concrate;
using BusinessLayer_HizmetPortal.ValidationRules;
using DataAcessLayer_HizmetPortal.Concrate;
using DataAcessLayer_HizmetPortal.EntityFramework;
using EntityLayer_HizmetPortal.Concrate;
using FluentValidation;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HizmetPortal.Controllers
{
    public class AdminHizmetlerController : Controller
    {
        HizmetlerManager hm = new HizmetlerManager(new EfHizmetlerDal());
        Context context = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var hizmetlers = hm.HizmetlerGetAll();
            return View(hizmetlers);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Hizmetler hizmetler)
        {
            if (Request.Files.Count > 0 && Request.Files[0] != null)
            {
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + dosyaAdi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                hizmetler.HizmetImage = "/Image/" + dosyaAdi + uzanti;
            }

            hm.HizmetlerAdd(hizmetler);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var hizmetlervalue = hm.HizmetlerGetById(id);
            return View(hizmetlervalue);
        }

        [HttpPost]
        public ActionResult Edit(Hizmetler hizmetler)
        {
            if (Request.Files.Count > 0 && Request.Files["HizmetImage"] != null)
            {
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Files["HizmetImage"].FileName);
                string uzanti = Path.GetExtension(Request.Files["HizmetImage"].FileName);
                string yol = "~/Image/" + dosyaAdi + uzanti;
                Request.Files["HizmetImage"].SaveAs(Server.MapPath(yol));
                hizmetler.HizmetImage = "/Image/" + dosyaAdi + uzanti;
            }
            hm.HizmetlerUpdate(hizmetler);
            return RedirectToAction("Index");
        }

        public ActionResult ToggleStatus(int id)
        {
            hm.HizmetlerToggleStatus(id);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var hizmetlervalues = hm.HizmetlerGetById(id);
            hm.HizmetlerDelete(hizmetlervalues);
            return RedirectToAction("Index");
        }
    }
}

HizmetPortal/Views/AdminHizmetler/Create.cshtml
@model EntityLayer_HizmetPortal.Concrate.Hizmetler

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Yeni Hizmet Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("Create", "AdminHizmetler", FormMethod.Post,new {enctype="multipart/form-data"}))
{
    <div class="form-group">
        @Html.Label("Hizmet Name")
        @Html.TextBoxFor(x => x.HizmetName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HizmetName)
        <br />
        @Html.Label("Hizmet Description")
        @Html.TextAreaFor(x => x.HizmetDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HizmetDescription)
        <br />
        @Html.Label("Hizmet Image")
        <input type="file" name="HizmetImage" />
        <br />
        <br />
        <button type="submit" class="btn btn-primary">Ekle</button>
    </div>
}

HizmetPortal/Views/AdminHizmetler/Edit.cshtml
@model EntityLayer_HizmetPortal.Concrate.Hizmetler

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Hizmetler Güncelleme Sayfası</h1>
<br />
@using (Html.BeginForm("Edit", "AdminHizmetler", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.Label("Hizmet Id")
        @Html.TextBoxFor(x => x.HizmetId, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Hizmet Name")
        @Html.TextBoxFor(x => x.HizmetName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Hizmet Description")
        @Html.TextAreaFor(x => x.HizmetDescription, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Hizmet Image")
        <input type="file" name="HizmetImage" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Güncelle</button>
}

HizmetPortal/Views/AdminHizmetler/Index.cshtml
@using EntityLayer_HizmetPortal.Concrate
@model List<Hizmetler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div style="overflow-x:auto;">
    <!-- Bu satır tabloyu sarmalayan div'in başlangıcı -->
    <table class="table table-bordered">
        <tr>
            <th>HizmetId</th>
            <th>HizmetName</th>
            <th>HizmetDescription</th>
            <th>HizmetImage</th>
            <th>HizmetStatus</th>
            <th>HizmetStatusButton</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.HizmetId</td>
                <td>
                    @(item.HizmetName != null ? (item.HizmetDescription.Length > 10 ? item.HizmetDescription.Substring(0, 10) + "..." : item.HizmetName) : "Bilgi yok")
                </td>
                <td>
                    @(item.HizmetDescription != null ? (item.HizmetDescription.Length > 20 ? item.HizmetDescription.Substring(0, 20) + "..." : item.HizmetDescription) : "Bilgi yok")
                </td>
                <td>@item.HizmetImage</td>
                <td>@item.HizmetStatus</td>
                <td>
                    @if (item.HizmetStatus)
                    {
                        <a href="/AdminHizmetler/ToggleStatus/@item.HizmetId" class="btn btn-danger">
                            Devre Dışı
                        </a>
                    }
                    else
                    {
                        <a href="/AdminHizmetler/ToggleStatus/@item.HizmetId" class="btn btn-success">
                            Aktif Et
                        </a>
                    }
                </td>
                <td><a href="/AdminHizmetler/Edit/@item.HizmetId" class="btn btn-warning">Güncelle</a></td>
                <td><a href="/AdminHizmetler/Delete/@item.HizmetId" class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </table>
</div> <!-- Bu satır tabloyu sarmalayan div'in sonu -->
<br />
<a href="/AdminHizmetler/Create" class="btn btn-info">Yeni Hizmet</a>