HizmetPortal/Controllers/AdminLoginController.cs
using DataAcessLayer_HizmetPortal.Concrate;
using EntityLayer_HizmetPortal.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HizmetPortal.Controllers
{
    public class AdminLoginController : Controller
    {
        // GET: AdminLogin
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Admin p)
        {
            Context context= new Context();
            var adminuserinfo = context.Admins.FirstOrDefault(x=>x.AdminMail == p.AdminMail && x.AdminPassword==p.AdminPassword);
            if (adminuserinfo!=null)
            {
                FormsAuthentication.SetAuthCookie(adminuserinfo.AdminMail, false);
                Session["AdminMail"] = adminuserinfo.AdminMail;
                return RedirectToAction("Index","AdminPersonel");
            }
            else
            {

                TempData["ErrorMessage"] = "Gecersiz kullanıcı adı veya sifre.";
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

HizmetPortal/Views/Shared/AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css" rel="stylesheet">
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-user-shield"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin Paneli</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">



            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <!-- Nav Item - Hizmetler -->
            <!-- Nav Item - Hizmetler 3 -->

            <style>
                .collapse-item {
                    color: white;
                }
            </style>


            <a class="btn btn-primary m-2" href="/AdminPersonel/Index/">Personel</a>
            <a class="btn btn-primary m-2" href="/AdminProject/Index/">Proje</a>
            <a class="btn btn-primary m-2" href="/AdminHaberler/Index/">Haberler</a>
            <a class="btn btn-primary m-2" href="/AdminStage/Index/">Proje Aşaması</a>
            <a class="btn btn-primary m-2" href="/AdminHizmetler/Index/">Hizmetler</a>
            <a class="btn btn-primary m-2" href="/AdminLesson/Index/">Dersler</a>
            <a class="btn btn-primary m-2" href="/AdminDuyurular/Index/">Duyurular</a>
            <a class="btn btn-primary m-2" href="/AdminGaleri/Index/">Galeri</a>
            <a class="btn btn-primary m-2" href="/AnaSayfa/AnaSayfaIndex/">AnaSayfa</a>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                @RenderBody()
            </div>
            <!-- End of Main Content -->
        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js"></script>
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-area-demo.js"></script>
    <script src="~/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-pie-demo.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

HizmetPortal/Views/Shared/AdminLayout2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Admin Paneli</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="~/Css/StyleSheet1.css" />
    <script src="~/Js/Duyuru.js"></script>
</head>
<body>
    <nav>
        <input type="checkbox" id="check" />
        <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
        </label>
        <label class="logo"><i class="fas fa-user-shield"></i>Admin Paneli</label>
        <ul>
            <li><a class="btn btn-primary m-2" href="/AdminPersonel/Index/">Personel</a></li>
            <li><a class="btn btn-primary m-2" href="/AdminProject/Index/">Proje</a></li>
            <li><a class="btn btn-primary m-2" href="/AdminHaberler/Index/">Haberler</a></li>
            <li><a class="btn btn-primary m-2" href="/AdminStage/Index/">Proje Aşaması</a></li>
            <li><a class="btn btn-primary m-2" href="/AdminHizmetler/Index/">Hizmetler</a></li>
            <li><a class="btn btn-primary m-2" href="/AdminLesson/Index/">Dersler</a></li>
            <li><a class="btn btn-primary m-2" href="/AdminDuyurular/Index/">Duyurular</a></li>
            <li><a class="btn btn-primary m-2" href="/AnaSayfa/AnaSayfaIndex/">AnaSayfa</a></li>
        </ul>
    </nav>

    <!-- Ana içerik alanı -->
    <div class="content">
        @RenderBody()
    </div>
</body>
</html>

HizmetPortal/Views/Shared/AdminLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Giriş</title>

    <!-- Bu şablon için özel fontlar -->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Bu şablon için özel stiller -->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Kart Gövdesi içinde iç içe satır -->
                <div class="row">
                    <div class="col-lg-6 d-none d-lg-block bg-login-image">
                        <img src="~/startbootstrap-sb-admin-2-gh-pages/img/Logot-Kare-Renkli-v1-2k.png" alt="Logo" style="width: 500px; height: 500px;">
                    </div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Hoşgeldiniz!</h1>
                            </div>
                            @using (Html.BeginForm("Index", "AdminLogin", FormMethod.Post))
                            {

                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" name="AdminMail" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Email Adresinizi Girin...">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-user" name="AdminPassword" id="exampleInputPassword" placeholder="Şifre">
                                </div>
                                <button type="submit" class="btn btn-primary btn-user btn-block">Giriş Yap</button>
                            }
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js"></script>
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Temel eklenti JavaScript -->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Tüm sayfalar için özel scriptler -->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js"></script>
    <script>
        $(document).ready(function() {
            var errorMessage = '@TempData["ErrorMessage"]';
            if (errorMessage) {
                alert(errorMessage);
            }
        });
    </script>
</body>
</html>

HizmetPortal/Views/Shared/UygulamaLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Talas İnovasyon Merkezi</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;400;700&family=Inter:wght@100;400;700&display=swap" rel="stylesheet">


    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" href="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/animate/animate.min.css" />
    <link href="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/LifeSure-1.0.057/LifeSure-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/LifeSure-1.0.057/LifeSure-1.0.0/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid topbar px-0 px-lg-4 bg-light py-2 d-none d-lg-block">
        <div class="container">
            <div class="row gx-0 align-items-center">
                <div class="col-lg-8 text-center text-lg-start mb-lg-0">
                    <div class="d-flex flex-wrap">
                        <div class="border-end border-primary pe-3">
                            <a href="tel:5555555555" class="text-muted small">
                                <i class="fas fa-phone-alt text-primary me-2"></i>555 555 55 55
                            </a>
                        </div>
                        <div class="ps-3">
                            <a href="mailto:example@gmail.com" class="text-muted small"><i class="fas fa-envelope text-primary me-2"></i>inovasyon@gmail.com</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 text-center text-lg-end">
                    <div class="d-flex justify-content-end">
                        <div class="d-flex border-end border-primary pe-3">
                            <a class="btn p-0 text-primary me-3" href="https://www.youtube.com/watch?v=EbP00AEBIVA"><i class="fab fa-instagram"></i></a>
                            <a class="btn p-0 text-primary me-0" href="#"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar & Hero Start -->
    <div class="container-fluid nav-bar px-0 px-lg-4 py-lg-0">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a href="/AnaSayfa/AnaSayfaIndex/" class="navbar-brand p-0">
                    <img src="~/Image/Logot-Kare-Renkli-v1-2k (1).png"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav">
                        <a href="/AnaSayfa/AnaSayfaIndex/" class="nav-item nav-link @(Request.Path == "/AnaSayfa/AnaSayfaIndex/" ? "active" : "")">Ana Sayfa</a>
                        <a href="/Hakkımızda/Index/" class="nav-item nav-link @(Request.Path == "/Hakkımızda/Index/" ? "active" : "")">Hakkımızda</a>
                        <a href="/Lesson/Index/" class="nav-item nav-link @(Request.Path == "/Lesson/Index/" ? "active" : "")">Dersler</a>
                        <a href="/Personel/Index/" class="nav-item nav-link @(Request.Path == "/Personel/Index/" ? "active" : "")">Personeller</a>
                        <a href="/Haberler/Index/" class="nav-item nav-link @(Request.Path == "/Haberler/Index/" ? "active" : "")">Haberler</a>
                        <a href="/Projeler/Index/" class="nav-item nav-link @(Request.Path == "/Projeler/Index/" ? "active" : "")">Projeler</a>
                        <a href="/Galeri/Index/" class="nav-item nav-link @(Request.Path == "/Galeri/Index/" ? "active" : "")">Galeri</a>
                        <a href="/Iletisim/Index/" class="nav-item nav-link @(Request.Path == "/Iletisim/Index/" ? "active" : "")">İletişim</a>
                    </div>
                    <!-- Optional: Admin Giriş button aligned right -->
                    <div class="nav-btn">
                        <a href="/AdminLogin/Index/" class="btn btn-primary rounded-pill py-2 px-4 ms-3 flex-shrink-0">Admin Giriş&nbsp;</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar & Hero End -->
    <!-- Sayfa içeriklerinin yer alacağı RenderBody metodu -->
    @RenderBody()

    <!-- Modal Search Start -->
    <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex align-items-center bg-primary">
                    <div class="input-group w-75 mx-auto d-flex">
                        <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1">
                        <span id="search-icon-1" class="btn bg-light border input-group-text p-3"><i class="fa fa-search"></i></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Search End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary btn-lg-square rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/wow/wow.min.js"></script>
    <script src="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/easing/easing.min.js"></script>
    <script src="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/waypoints/waypoints.min.js"></script>
    <script src="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/counterup/counterup.min.js"></script>
    <script src="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/LifeSure-1.0.057/LifeSure-1.0.0/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/LifeSure-1.0.057/LifeSure-1.0.0/js/main.js"></script>
</body>
</html>

HizmetPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>